### PR TITLE
Add support for mesurementMappings in the InfluxDB reporter config

### PR DESCRIPTION
**Pull request by jimlar**
I want to use this for publishing Cassandra metrics and need to use the measurementMappings to group metrics, to avoid getting too fine grained ones.

Let me know if something is missing.
/BR Jimmy

### CODE REVIEW

**Comment by yuesong** [comment]
Thanks for the PR. I don't have enough knowledge about the influxdb support. Perhaps @mmatloka wouldn't mind reviewing this?

**Comment by mmatloka** [comment]
Sure, I'll look at this during the weekend.

**Comment by mmatloka** [comment]
Looks good 👍

**Comment by yuesong** [comment]
@mmatloka Thanks!

**Comment by congshenV** [comment]
@mmatloka I want to use measurmentMapping to do group mapping, but it is an error. The error is:

WARN  [main] 2018-04-18 17:38:47,255 CassandraDaemon.java:385 - Failed to load metrics-reporter-config, metric sinks will not be activated
org.yaml.snakeyaml.constructor.ConstructorException: null; Can't construct a java object for tag:yaml.org,2002:com.addthis.metrics3.reporter.config.ReporterConfig; exception=Cannot create property=influxdb for JavaBean=com.addthis.metrics3.reporter.config.ReporterConfig@54b858b4; Cannot create property=MeasurementMappings for JavaBean=com.addthis.metrics3.reporter.config.InfluxDBReporterConfig@bf2e303; Unable to find property 'MeasurementMappings' on class: com.addthis.metrics3.reporter.config.InfluxDBReporterConfig;  in 'reader', line 24, column 1:

please help me  find the problem，thanks！

**Pull request merged**
